version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '23:00'
      timezone: Asia/Kolkata
    open-pull-requests-limit: 3
    labels:
      - dependencies
    reviewers:
      - 'shivam-sharma7'
